baseURL: ""
languageCode: en-us
title: pianorganic
theme: PaperMod

params:
  homeInfoParams:
    Title: "Добро пожаловать в Pianorganic"
    Content: Осмысляем игру на фортепиано
  socialIcons:
    - name: vk
      url: "https://vk.com"
    - name: telegram
      url: "https://t.me/pianorganic"
      
  cover:
    linkFullImages: true
  ShowBreadCrumbs: true


menu: 
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30


